name: Deploy static HTML

on:
  workflow_dispatch: {}
  push:
    branches:
      - dynamic

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Python
        uses: actions/setup-python@v6
      - name: Checkout dynamic branch
        uses: actions/checkout@v6
        with:
          ref: dynamic
          path: dynamic
      - name: Checkout static branch
        uses: actions/checkout@v6
        with:
          ref: static
          path: static
      - name: Generate static files
        run: |
          cd dynamic/
          python3 updatehtml.py
          rm -rf *.in *.py contents/
          cd ../
      - name: Detect changes
        id: check_changes
        run: |
          cd static/
          rm -rf *
          cp -r ../dynamic/* .
          if git diff --quiet ; then
            echo "Already up-to-date"
            echo "UPDATEHTML=false" >> "$GITHUB_ENV"
          else
            echo "New modifications"
            echo "UPDATEHTML=true" >> "$GITHUB_ENV"
          fi
          cd ../
      - name: Update static branch
        if: ${{ env.UPDATEHTML == 'true' }}
        run: |
          cd static/
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 711 {} \;
          git config --global user.name "Per4ML"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Generated static from dynamic"
          git push origin static
          cd ../
      - name: Upload static HTML
        if: ${{ env.UPDATEHTML == 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'static/'
      - name: Deploy to GitHub Pages
        if: ${{ env.UPDATEHTML == 'true' }}
        id: deployment
        uses: actions/deploy-pages@v4
