name: Deploy static HTML

on:
  workflow_dispatch: {}
  push:
    branches:
      - dynamic

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Python
        uses: actions/setup-python@v6
      - name: Checkout dynamic branch
        uses: actions/checkout@v6
        with:
          ref: dynamic
          path: dynamic
      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          ref: main
          path: main
      - name: Generate static files
        run: |
          cd dynamic/
          python3 updatehtml.py
          rm -rf *.in *.py contents/
          cd ../
      - name: Detect changes
        id: check_changes
        run: |
          cd main/
          rm -rf *
          cp -r ../dynamic/* .
          if git diff --quiet ; then
            echo "Already up-to-date"
            echo "UPDATEHTML=false" >> "$GITHUB_ENV"
          else
            echo "New modifications"
            echo "UPDATEHTML=true" >> "$GITHUB_ENV"
          fi
          cd ../
      - name: Update main branch
        if: ${{ env.UPDATEHTML == 'true' }}
        run: |
          cd main/
          git config --global user.name "Per4ML"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Generated main from dynamic"
          git push origin main
          cd ../
