name: Deploy static HTML

on:
  workflow_dispatch: {}
  push:
    branches:
      - dynamic

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v6
    - uses: actions/checkout@v6
      with:
        ref: dynamic
        path: dynamic
    - uses: actions/checkout@v6
      with:
        ref: main
        path: main
    - name: Generate HTML from infiles
      run: |
        cd dynamic/
        python3 updatehtml.py
        mv *.html ../main/
        cd ../
    - name: Detect changes
      id: check_changes
      run: |
        cd main/
        if git diff --quiet ; then
          echo "Already up-to-date"
          echo "::set-output name=changed::false"
        else
          echo "New modifications"
          echo "::set-output name=changed::true"
        fi
        cd ../
    - name: Update main
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        cd main/
        #git config --global user.name "${{ github.actor }}"
        #git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git config user.email "{user.id}+{user.login}@users.noreply.github.com"
        #git switch main
        #git merge dynamic
        #git push origin main
        git add *.html
        git commit -m 'genstatic'
        git push
